substitutions:
  base_version: 0.1

text_sensor:
  - platform: template
    name: "Mod Version Base"
    entity_category: diagnostic
    lambda: |-
      return "${base_version}";

esphome:
  name: "${device_name}"
  friendly_name: "${friendly_name}"
  name_add_mac_suffix: true

logger:
  level: INFO

ota:
  - platform: esphome

web_server:
  port: 80

captive_portal:

