substitutions:
  diagnostic_version: 0.1

text_sensor:
  - platform: template
    name: "Mod Version Diagnostic"
    entity_category: diagnostic
    lambda: |-
      return "${diagnostic_version}";

  - platform: template
    name: "Board Id"
    id: board_id
    entity_category: diagnostic
    lambda: |-
      return {"${BOARD_ID}"};

  - platform: template
    name: "Board Name"
    id: board_name
    entity_category: diagnostic
    lambda: |-
      return {"${board_name}"};

  - platform: wifi_info
    ip_address:
      name: "IP Address"

    mac_address:
      name: "MAC Address"

    ssid:
      name: "WiFi SSID"

    bssid:
      name: "WiFi BSSID"

    dns_address:
      name: "DNS Server"

  - platform: template
    name: "Build Date"
    entity_category: diagnostic
    lambda: |-
      const char *months = "JanFebMarAprMayJunJulAugSepOctNovDec";
      const char *m = strstr(months, __DATE__);

      int month = m ? ((m - months) / 3) + 1 : 0;
      int day = atoi(__DATE__ + 4);
      int year = atoi(__DATE__ + 7);

      char result[20];
      snprintf(
        result,
        sizeof(result),
        "%04d-%02d-%02d %s",
        year,
        month,
        day,
        __TIME__
      );

      return {result};

  - platform: version
    name: "ESPHome Version"

  - platform: template
    name: "Device Name"
    lambda: |-
      return {"${device_name}"};

  - platform: template
    name: "Friendly Name"
    lambda: |-
      return {"${friendly_name}"};

sensor:
  - platform: wifi_signal
    name: "WiFi RSSI"
    id: wifi_rssi
    update_interval: 30s

  - platform: copy
    source_id: wifi_rssi
    name: "WiFi Quality"
    unit_of_measurement: "%"
    entity_category: diagnostic
    filters:
      - lambda: |-
          return min(max(2.0f * (x + 100.0f), 0.0f), 100.0f);

  - platform: uptime
    name: "Uptime"
    update_interval: 60s
