esphome:
  name: esp32-c6-ble
  friendly_name: ESP32 C6 BLE

esp32:
  board: esp32-c6-devkitm-1
  variant: esp32c6
  framework:
    type: esp-idf

logger:
  level: VERY_VERBOSE

wifi:
  ssid: !secret wifi_homefcsiot_ssid
  password: !secret wifi_homefcsiot_password

  ap:
    ssid: "BLE-Gateway"
    password: !secret wifi_ap_password
    
captive_portal:

ota:
  - platform: esphome

esp32_ble_tracker:
  scan_parameters:
    interval: 320ms
    window: 300ms
    active: true

text_sensor:
  - platform: ble_scanner
    name: "BLE Scanner"

