import React from "react";
import { ActionIcon, Button, Checkbox, Group, Modal, NumberInput, Select, Stack, Table, Text, Textarea, TextInput, Tooltip } from "@mantine/core";
import type { ServiceRegistryAccessLink } from "./types";
import { DeleteActionIcon, EditActionIcon } from "./TableActionIcons";
import { DEVICE_ICON_OPTIONS, DeviceGlyph } from "./DeviceGlyph";
import { openDeviceAccessUrl } from "./DeviceAccessLinksEditor";

export interface ServiceAccessContext { serviceName:string; provider:string; serviceClass:string; serviceType:string; }
interface LinkForm { name:string; linkType:string; urlTemplate:string; username:string; port:number|string; parametersText:string; icon:string; color:string; enabled:boolean; sortOrder:number|string; }
const LINK_TYPES=["WEB","SSH","API","DOCUMENTATION","CUSTOM"].map(value=>({value,label:value}));
const COLORS=["blue","cyan","grape","green","indigo","lime","orange","pink","red","teal","violet","yellow"].map(value=>({value,label:value[0]!.toUpperCase()+value.slice(1)}));
const emptyLink=():LinkForm=>({name:"",linkType:"WEB",urlTemplate:"https://",username:"",port:"",parametersText:"",icon:"globe",color:"blue",enabled:true,sortOrder:100});
function paramsFromText(text:string){const r:Record<string,string>={};for(const line of text.split(/\r?\n/).map(v=>v.trim()).filter(Boolean)){const i=line.indexOf("=");if(i>0)r[line.slice(0,i).trim()]=line.slice(i+1).trim();}return r;}
function paramsToText(value:Record<string,string>){return Object.entries(value??{}).map(([k,v])=>`${k}=${v}`).join("\n");}
export function resolveServiceAccessUrl(link:ServiceRegistryAccessLink,context:ServiceAccessContext){const values:Record<string,string>={service_name:context.serviceName,provider:context.provider,class:context.serviceClass,type:context.serviceType,username:link.username??"",port:link.port==null?"":String(link.port)};for(const[k,v]of Object.entries(link.parameters??{}))values[`param:${k}`]=v;const missing=new Set<string>();const url=link.urlTemplate.replace(/\{\{([^{}]+)\}\}/g,(_m,key:string)=>{const v=values[key];if(v==null||v==="")missing.add(key);return v??"";});return{url,unresolved:[...missing]};}
export function ServiceAccessLinksEditor({value,onChange,context}:{value:ServiceRegistryAccessLink[];onChange:(v:ServiceRegistryAccessLink[])=>void;context:ServiceAccessContext}){
 const[opened,setOpened]=React.useState(false);const[index,setIndex]=React.useState<number|null>(null);const[form,setForm]=React.useState<LinkForm>(emptyLink());
 const openCreate=()=>{setIndex(null);setForm(emptyLink());setOpened(true);}; const openEdit=(i:number)=>{const x=value[i]!;setIndex(i);setForm({name:x.name,linkType:x.linkType,urlTemplate:x.urlTemplate,username:x.username??"",port:x.port??"",parametersText:paramsToText(x.parameters),icon:x.icon,color:x.color,enabled:x.enabled,sortOrder:x.sortOrder});setOpened(true);};
 const save=()=>{const item:ServiceRegistryAccessLink={name:form.name.trim(),linkType:form.linkType,urlTemplate:form.urlTemplate.trim(),username:form.username.trim()||null,port:typeof form.port==="number"?form.port:null,parameters:paramsFromText(form.parametersText),icon:form.icon,color:form.color,enabled:form.enabled,sortOrder:typeof form.sortOrder==="number"?form.sortOrder:100};const next=[...value];if(index==null)next.push(item);else next[index]=item;next.sort((a,b)=>a.sortOrder-b.sortOrder||a.name.localeCompare(b.name));onChange(next);setOpened(false);};
 const previewLink:ServiceRegistryAccessLink={name:form.name,linkType:form.linkType,urlTemplate:form.urlTemplate,username:form.username||null,port:typeof form.port==="number"?form.port:null,parameters:paramsFromText(form.parametersText),icon:form.icon,color:form.color,enabled:form.enabled,sortOrder:typeof form.sortOrder==="number"?form.sortOrder:100}; const preview=resolveServiceAccessUrl(previewLink,context);
 return <Stack gap="xs"><Group justify="space-between"><div><Text fw={600} size="sm">Access links</Text><Text size="xs" c="dimmed">Web, API, documentation or custom launch URLs. Passwords are not stored here.</Text></div><Button size="compact-xs" variant="light" onClick={openCreate}>+ Add access</Button></Group>
 {value.length>0?<Table withTableBorder><Table.Thead><Table.Tr><Table.Th>Name</Table.Th><Table.Th>Type</Table.Th><Table.Th>Template</Table.Th><Table.Th>User</Table.Th><Table.Th>Actions</Table.Th></Table.Tr></Table.Thead><Table.Tbody>{value.map((x,i)=>{const r=resolveServiceAccessUrl(x,context);return <Table.Tr key={`${x.name}-${i}`}><Table.Td><Group gap="xs"><DeviceGlyph icon={x.icon} color={x.color}/><Text size="sm">{x.name}</Text></Group></Table.Td><Table.Td>{x.linkType}</Table.Td><Table.Td><Tooltip label={r.unresolved.length?`Missing: ${r.unresolved.join(", ")}`:r.url}><Text size="xs" ff="monospace" lineClamp={1}>{x.urlTemplate}</Text></Tooltip></Table.Td><Table.Td>{x.username??"—"}</Table.Td><Table.Td><Group gap={4}><ActionIcon variant="subtle" disabled={!x.enabled||r.unresolved.length>0} onClick={()=>openDeviceAccessUrl(r.url,`ss_service_${context.serviceName}_${i}`)}><DeviceGlyph icon={x.icon} color={x.color}/></ActionIcon><EditActionIcon onClick={()=>openEdit(i)}/><DeleteActionIcon onClick={()=>onChange(value.filter((_,n)=>n!==i))}/></Group></Table.Td></Table.Tr>;})}</Table.Tbody></Table>:<Text size="sm" c="dimmed">No access links configured.</Text>}
 <Modal opened={opened} onClose={()=>setOpened(false)} title={index==null?"Add access link":"Edit access link"} size="lg"><Stack gap="sm"><Group grow><TextInput label="Name" required autoFocus value={form.name} onChange={e=>setForm(f=>({...f,name:e.currentTarget.value}))}/><Select label="Type" data={LINK_TYPES} value={form.linkType} onChange={v=>setForm(f=>({...f,linkType:v??"CUSTOM"}))}/></Group><Textarea label="URL template" required minRows={2} value={form.urlTemplate} onChange={e=>setForm(f=>({...f,urlTemplate:e.currentTarget.value}))} description="Placeholders: {{service_name}}, {{provider}}, {{class}}, {{type}}, {{username}}, {{port}}, {{param:key}}"/><Group grow><TextInput label="Username" value={form.username} onChange={e=>setForm(f=>({...f,username:e.currentTarget.value}))}/><NumberInput label="Port" min={1} max={65535} value={form.port} onChange={v=>setForm(f=>({...f,port:v}))}/></Group><Textarea label="Custom parameters" minRows={2} value={form.parametersText} onChange={e=>setForm(f=>({...f,parametersText:e.currentTarget.value}))}/><Group grow><Select label="Icon" searchable data={DEVICE_ICON_OPTIONS} value={form.icon} leftSection={<DeviceGlyph icon={form.icon} color={form.color} size={16}/>} renderOption={({option})=><Group gap="xs"><DeviceGlyph icon={option.value} color={form.color} size={16}/><Text size="sm">{option.label}</Text></Group>} onChange={v=>setForm(f=>({...f,icon:v??"link"}))}/><Select label="Color" data={COLORS} value={form.color} leftSection={<DeviceGlyph icon={form.icon} color={form.color} size={16}/>} onChange={v=>setForm(f=>({...f,color:v??"blue"}))}/><NumberInput label="Sort order" min={0} value={form.sortOrder} onChange={v=>setForm(f=>({...f,sortOrder:v}))}/></Group><Checkbox label="Enabled" checked={form.enabled} onChange={e=>setForm(f=>({...f,enabled:e.currentTarget.checked}))}/><Text size="xs" ff="monospace" c={preview.unresolved.length?"orange":"dimmed"}>{preview.url||"—"}</Text>{preview.unresolved.length>0&&<Text size="xs" c="orange">Unresolved: {preview.unresolved.join(", ")}</Text>}<Group justify="flex-end"><Button variant="default" onClick={()=>setOpened(false)}>Cancel</Button><Button disabled={!form.name.trim()||!form.urlTemplate.trim()} onClick={save}>Save</Button></Group></Stack></Modal></Stack>;
}
